version: '3'
services:
  web_service:
    build: .
    environment:
    - LD_LIBRARY_PATH=/home/cjones/instantclient_12_2
    - PATH=/home/cjones/instantclient_12_2:$PATH
    ports:
    - "3010:3009"
    links:
    - instant_client
  instant_client:
    image: store/oracle/database-instantclient:12.2.0.1
  